/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-14 15:36:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ClientSignupView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/annakim/Downloads/tomcat/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("file:/Users/annakim/Downloads/tomcat/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1664823970000L));
    _jspx_dependants.put("/Nav2.jsp", Long.valueOf(1668395386000L));
    _jspx_dependants.put("/Foot.jsp", Long.valueOf(1668330809000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Detail View - ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DetailView.regName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.2/examples/navbar-fixed/\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("@import\n");
      out.write("	url('https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800')\n");
      out.write("	;\n");
      out.write("\n");
      out.write("@import\n");
      out.write("	url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script src=\"js/jquery-3.6.0.min.js\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script>\n");
      out.write("	//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\n");
      out.write("	function sample4_execDaumPostcode() {\n");
      out.write("		new daum.Postcode(\n");
      out.write("				{\n");
      out.write("					oncomplete : function(data) {\n");
      out.write("						// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\n");
      out.write("\n");
      out.write("						// 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\n");
      out.write("						// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\n");
      out.write("						var roadAddr = data.roadAddress; // 도로명 주소 변수\n");
      out.write("						var extraRoadAddr = ''; // 참고 항목 변수\n");
      out.write("\n");
      out.write("						// 법정동명이 있을 경우 추가한다. (법정리는 제외)\n");
      out.write("						// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\n");
      out.write("						if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\n");
      out.write("							extraRoadAddr += data.bname;\n");
      out.write("						}\n");
      out.write("						// 건물명이 있고, 공동주택일 경우 추가한다.\n");
      out.write("						if (data.buildingName !== '' && data.apartment === 'Y') {\n");
      out.write("							extraRoadAddr += (extraRoadAddr !== '' ? ', '\n");
      out.write("									+ data.buildingName : data.buildingName);\n");
      out.write("						}\n");
      out.write("						// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\n");
      out.write("						if (extraRoadAddr !== '') {\n");
      out.write("							extraRoadAddr = ' (' + extraRoadAddr + ')';\n");
      out.write("						}\n");
      out.write("\n");
      out.write("						// 우편번호와 주소 정보를 해당 필드에 넣는다.\n");
      out.write("						document.getElementById('sample4_postcode').value = data.zonecode;\n");
      out.write("						document.getElementById(\"sample4_roadAddress\").value = roadAddr;\n");
      out.write("						document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\n");
      out.write("\n");
      out.write("						// 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\n");
      out.write("						if (roadAddr !== '') {\n");
      out.write("							document.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\n");
      out.write("						} else {\n");
      out.write("							document.getElementById(\"sample4_extraAddress\").value = '';\n");
      out.write("						}\n");
      out.write("\n");
      out.write("						var guideTextBox = document.getElementById(\"guide\");\n");
      out.write("						// 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\n");
      out.write("						if (data.autoRoadAddress) {\n");
      out.write("							var expRoadAddr = data.autoRoadAddress\n");
      out.write("									+ extraRoadAddr;\n");
      out.write("							guideTextBox.innerHTML = '(예상 도로명 주소 : '\n");
      out.write("									+ expRoadAddr + ')';\n");
      out.write("							guideTextBox.style.display = 'block';\n");
      out.write("\n");
      out.write("						} else if (data.autoJibunAddress) {\n");
      out.write("							var expJibunAddr = data.autoJibunAddress;\n");
      out.write("							guideTextBox.innerHTML = '(예상 지번 주소 : '\n");
      out.write("									+ expJibunAddr + ')';\n");
      out.write("							guideTextBox.style.display = 'block';\n");
      out.write("						} else {\n");
      out.write("							guideTextBox.innerHTML = '';\n");
      out.write("							guideTextBox.style.display = 'none';\n");
      out.write("						}\n");
      out.write("					}\n");
      out.write("				}).open();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- 성연씨가 작업해주신 정규식  -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	function checkMember() {\n");
      out.write("\n");
      out.write("		var regExpcId = /^[a-zA-Z0-9]*$/\n");
      out.write("		var regExpcName = /^[가-힣]*$/\n");
      out.write("		var regExpcPw = /^[a-zA-Z0-9]*$/\n");
      out.write("		var regExpcPw2 = /^[a-zA-Z0-9]*$/\n");
      out.write("		var regExpcPhone = /^\\d{3}-\\d{3,4}-\\d{4}$/\n");
      out.write("		var regExpcEmail = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/i\n");
      out.write("\n");
      out.write("		var form = document.Member\n");
      out.write("\n");
      out.write("		var cId = form.cId.value\n");
      out.write("		var cName = form.cName.value\n");
      out.write("		var cPw = form.cPw.value\n");
      out.write("		var cPw2 = form.cPw2.value\n");
      out.write("		var cPhone = form.cPhone.value\n");
      out.write("		var cEmail = form.cEmail.value\n");
      out.write("\n");
      out.write("		if (!regExpcId.test(cId)) {\n");
      out.write("			alert(\"아이디는 숫자와 영문으로만 작성해주세요.\")\n");
      out.write("			form.cId.select()\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (cId == \"\") {\n");
      out.write("			alert(\"아이디를 입력해주세요.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (cId == \"\") {\n");
      out.write("			alert(\"공백입니다 입력해주세요.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		if (!regExpcName.test(cName)) {\n");
      out.write("			alert(\"이름은 한글으로만 입력해 주세요.\")\n");
      out.write("			form.cName.select()\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (cName == \"\") {\n");
      out.write("			alert(\"이름을 입력해주세요.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		if (!regExpcPw.test(cPw)) {\n");
      out.write("			alert(\"비밀번호는 영문과 숫자만으로 입력해 주세요.\")\n");
      out.write("			form.cPw.select()\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (cPw == \"\") {\n");
      out.write("			alert(\"비밀번호를 입력해주세요.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (!regExpcPw2.test(cPw2)) {\n");
      out.write("			alert(\"비밀번호는 영문과 숫자만으로 입력해 주세요.\")\n");
      out.write("			form.cPw2.select()\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (cPw2 == \"\") {\n");
      out.write("			alert(\"비밀번호를 입력해주세요.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		if (cPw != cPw2) {\n");
      out.write("			alert(\"비밀번호가 일치하지 않습니다.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		if (!regExpcPhone.test(cPhone)) {\n");
      out.write("			alert(\"전화번호 형식으로 입력해주세요.\")\n");
      out.write("			form.cPhone.select()\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (cPhone == \"\") {\n");
      out.write("			alert(\"전화번호를 입력해주세요.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		if (!regExpcEmail.test(cEmail)) {\n");
      out.write("			alert(\"이메일 형식으로 입력해주세요.\")\n");
      out.write("			form.cEmail.select()\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("		if (cEmail == \"\") {\n");
      out.write("			alert(\"이메일을 입력해주세요.\")\n");
      out.write("			return false\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		form.submit()\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- Header Start -->\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" >\n");
      out.write("<style type=\"text/css\">\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800'); \n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Ubuntu&display=swap');\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 2022-11-8 Hosik - Hoping svg 클릭시 메인화면으로 링크 달았음 --> \n");
      out.write("	<!-- 2022-11-9 Hosik - 성연씨 코드 받고 회원메뉴 부분 수정함.\n");
      out.write("						 - 로그인이 안되어 있을시 로그인 및 회원가입 메뉴 \n");
      out.write("						 - 로그인 세션이 있을경우 메뉴가 회원정보수정-탈퇴 , 로그아웃 그리고 예약정보확인 페이지 등록예정 \n");
      out.write("		2022-11-10 Hosik - Created Navbar2 기존 Navbar에서 검색기능을 없앤 navbar의 필요성을 느껴서 생성 					 	\n");
      out.write("						 \n");
      out.write("							 --> \n");
      out.write("							 \n");
      out.write("	");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("	   <header class=\"d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom\">\n");
      out.write("	     <a href=\"main.do\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none\">\n");
      out.write("	       <svg class=\"mysvg\" xmlns=\"http://www.w3.org/2000/svg\" width=\"28\" height=\"28\" fill=\"currentColor\" class=\"bi bi-house-heart\" viewBox=\"0 0 16 16\">\n");
      out.write("		  <path d=\"M8 6.982C9.664 5.309 13.825 8.236 8 12 2.175 8.236 6.336 5.309 8 6.982Z\"/>\n");
      out.write("		  <path d=\"M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.707L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.646a.5.5 0 0 0 .708-.707L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z\"/>\n");
      out.write("		</svg>\n");
      out.write("	       <span class=\"mytitle\"><b>Hoping</b></span>\n");
      out.write("	     </a>\n");
      out.write("	     \n");
      out.write("	     <ul class=\"nav nav-pills\">\n");
      out.write("	     	<li class=\"nav-item\" style=\"font-size: 14px;\">\n");
      out.write("	     		<!-- <a href=\"../../../../Host/src/main/webapp/HostTerms.jsp\" class=\"link-dark nav-link\">호스트 모드</a> -->\n");
      out.write("	     		\n");
      out.write("	     	");
 if (session.getAttribute("CID") != null) { 
      out.write("\n");
      out.write("	     		<a href=\"../joohyuncamping/check.do?cId=");
      out.print((String) session.getAttribute("CID"));
      out.write("\" class=\"link-dark nav-link\">호스트 모드로 전환하기</a>\n");
      out.write("	     			  ");
 } 
      out.write("	\n");
      out.write("	     	</li>\n");
      out.write("	     	\n");
      out.write("	     	<li class=\"nav-item\">\n");
      out.write("				<svg class=\"dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" xmlns=\"http://www.w3.org/2000/svg\" width=\"28\" height=\"28\" fill=\"currentColor\" class=\"bi bi-person-lines-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("					<path d=\"M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z\"/>\n");
      out.write("				</svg>\n");
      out.write("				<ul class=\"dropdown-menu\">\n");
      out.write("				");
 if (session.getAttribute("cId") == null) { 
      out.write("\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"ClientLoginView.jsp\">로그인</a></li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"ClientSignupView.jsp\">회원가입</a></li>\n");
      out.write("			       ");
 } else { 
			       
      out.write("\n");
      out.write("			    <li>");
      out.print(session.getAttribute("cId")  );
      out.write(" 님 환영합니다 </li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"#\">예약 정보 관리</a></li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"#\">위시 리스트</a></li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"mypageView.do\">마이페이지</a></li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"ClientLogout.jsp\">로그아웃</a></li>\n");
      out.write("			    \n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("			  </ul>\n");
      out.write("			</li>\n");
      out.write("	     </ul>\n");
      out.write("	   </header>\n");
      out.write(" 	</div>\n");
      out.write("\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<!-- Header End -->\n");
      out.write("	<!-- Main Start -->\n");
      out.write("	<main>\n");
      out.write("		<div class=\"container-md d-flex justify-content-center\">\n");
      out.write("		 <div class=\"row\">\n");
      out.write("		 <div class=\"col\">\n");
      out.write("				\n");
      out.write("				<form name=\"Member\" action=\"Clientwrite.do\" method=\"post\">\n");
      out.write("					<table>\n");
      out.write("						<tr>\n");
      out.write("							<th >아이디</th>\n");
      out.write("							<td><!-- <input type=\"text\" name=\"cId\" class=\"input_id\"> -->\n");
      out.write("							<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\n");
      out.write("						\n");
      out.write("							<input type=\"text\" name=\"cId\" class=\"cId\" placeholder=\"ex ) camp12\" required=\"required\">\n");
      out.write("							<font id=\"checkId\" size=\"2\"></font>\n");
      out.write("							\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("\n");
      out.write("						<tr>\n");
      out.write("							<th>비밀번호</th>\n");
      out.write("							<td>	\n");
      out.write("								<input type=\"password\" name=\"cPw\" id=\"password_1\" class=\"pw\"\n");
      out.write("									placeholder=\"ex) ld1397\">\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("\n");
      out.write("						<tr>\n");
      out.write("							<th>비밀번호 확인</th>\n");
      out.write("							<td>\n");
      out.write("								<input type=\"password\" name=\"cPw2\" id=\"password_2\" class=\"pw\" placeholder=\"ex) ld1397\"> \n");
      out.write("								<span id=\"alert-success\" style=\"display: none;\">\n");
      out.write("									<font size=\"2\">비밀번호가 일치합니다.</font>\n");
      out.write("								</span> \n");
      out.write("								<span id=\"alert-danger\" style=\"display: none; font-weight:;\">\n");
      out.write("								<font size=\"2\" color=\"#d92742\">비밀번호가 일치하지 않습니다.</font>\n");
      out.write("								</span>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>이름</th>\n");
      out.write("							<td><input type=\"text\" name=\"cName\" size=\"40\" placeholder= \"한글로 이름을 작성해 주세요\"></td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>전화번호</th>\n");
      out.write("							<th><input type=\"text\" name=\"cPhone\" size=\"40\"></th>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<th>이메일</th>\n");
      out.write("							<td><input type=\"text\" name=\"cEmail\" size=\"40\" placeholder= \"example@example.com / E-mail 형식으로 작성해주세요 \"></td>\n");
      out.write("						</tr>\n");
      out.write("\n");
      out.write("						<tr>\n");
      out.write("							<th>주소</th>\n");
      out.write("							<td><input type=\"text\" id=\"sample4_postcode\"\n");
      out.write("								placeholder=\"우편번호\" name=\"zonecode\"> <input type=\"button\"\n");
      out.write("								onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\n");
      out.write("								<input type=\"text\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\" name=\"address\"><br>\n");
      out.write("								<input type=\"text\" id=\"sample4_jibunAddress\" placeholder=\"빌딩이름\" name=\"buildingAddress\">\n");
      out.write("								<input type=\"text\" id=\"sample4_detailAddress\" placeholder=\"상세주소\" name=\"detailAddress\"></td>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td colspan=\"2\">\n");
      out.write("								<div class=\"container-md d-flex justify-content-center\">\n");
      out.write("									<input type=\"button\" value=\"회원가입\"  class=\"btn btn-primary\"\n");
      out.write("								onclick=\"checkMember()\" style=\"WIDTH: 210pt; HEIGHT: 40pt\">\n");
      out.write("								</div>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("					</table>\n");
      out.write("				</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- DIV row End -->\n");
      out.write("		<!-- DIV container End -->\n");
      out.write("	</main>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("		\n");
      out.write("	<script>\n");
      out.write("		$('.pw').focusout(function() {\n");
      out.write("			var pwd1 = $(\"#password_1\").val();\n");
      out.write("			var pwd2 = $(\"#password_2\").val();\n");
      out.write("\n");
      out.write("			if (pwd1 != '' && pwd2 == '') {\n");
      out.write("				null;\n");
      out.write("			} else if (pwd1 != \"\" || pwd2 != \"\") {\n");
      out.write("				if (pwd1 == pwd2) {\n");
      out.write("					$(\"#alert-success\").css('display', 'inline-block');\n");
      out.write("					$(\"#alert-danger\").css('display', 'none');\n");
      out.write("				} else {\n");
      out.write("					/* alert(\"비밀번호가 일치하지 않습니다. 비밀번호를 재확인해주세요\"); */\n");
      out.write("					$(\"#alert-success\").css('display', 'none');\n");
      out.write("					$(\"#alert-danger\").css('display', 'inline-block');\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("	<!--  <script src = \"js/jquery-3.6.0.min.js\"></script> -->\n");
      out.write("	<script>\n");
      out.write("		$('.cId').focusout(function() {\n");
      out.write("			let cId = $('.cId').val(); // input_id에 입력되는 값\n");
      out.write("\n");
      out.write("			$.ajax({\n");
      out.write("				url : \"./IdCheckService\",\n");
      out.write("				type : \"post\",\n");
      out.write("				data : {\n");
      out.write("					cId : cId\n");
      out.write("				},\n");
      out.write("				dataType : 'json',\n");
      out.write("				success : function(result) {\n");
      out.write("					if (result == 0) {\n");
      out.write("						$(\"#checkId\").html('중복된 아이디입니다.');\n");
      out.write("						$(\"#checkId\").attr('color', 'red');\n");
      out.write("						$(':text:not([id=cName]):not([id=cPhone])').val('');\n");
      out.write("						alert(\"중복된 아이디입니다. 다시 입력해주세요.\")\n");
      out.write("\n");
      out.write("					} else {\n");
      out.write("						$(\"#checkId\").html('중복되지 않은 아이디입니다.');\n");
      out.write("						$(\"#checkId\").attr('color', 'green');\n");
      out.write("					}\n");
      out.write("				},\n");
      out.write("				error : function() {\n");
      out.write("					alert(\"서버요청실패\");\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("\n");
      out.write("		})\n");
      out.write("	</script>\n");
      out.write("		\n");
      out.write("	<!-- Foot -->\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<style>\n");
      out.write("/* pc 화면 */\n");
      out.write("@media (min-width: 768px) {\n");
      out.write("    #kakao-talk-channel-chat-button {\n");
      out.write("    position: fixed;\n");
      out.write("    z-index: 999;\n");
      out.write("    right: 30px; /* 화면 오른쪽으로부터의 거리, 숫자만 변경 */\n");
      out.write("    bottom: 30px; /* 화면 아래쪽으로부터의 거리, 숫자만 변경 */\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("/* 모바일 화면 */\n");
      out.write("@media (max-width:767px) {\n");
      out.write("    #kakao-talk-channel-chat-button {\n");
      out.write("    position: fixed;\n");
      out.write("    z-index: 999;\n");
      out.write("    right: 15px; /* 화면 오른쪽으로부터의 거리, 숫자만 변경 */\n");
      out.write("    bottom: 30px; /* 화면 아래쪽으로부터의 거리, 숫자만 변경 */\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("	<!-- \n");
      out.write("	2022-11-08 Hosik - 우측하단 카카오톡 1:1 채팅 DIV 추가 \n");
      out.write("		 11-11 Hosik - 강사님이 빼라고 하셔서 뺌 \n");
      out.write("	 -->\n");
      out.write("<!-- 	\n");
      out.write("<div id=\"kakao-talk-channel-chat-button\"></div>\n");
      out.write("\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\n");
      out.write("<script type='text/javascript'>\n");
      out.write("  //<![CDATA[\n");
      out.write("    // 사용할 앱의 JavaScript 키를 설정해 주세요.\n");
      out.write("    Kakao.init('8d20a512bea587bcc64da4d1d6a184b3');\n");
      out.write("    // 카카오톡 채널 1:1채팅 버튼을 생성합니다.\n");
      out.write("    Kakao.Channel.createChatButton({\n");
      out.write("      container: '#kakao-talk-channel-chat-button',\n");
      out.write("      channelPublicId: '_cxfgGxj' // 카카오톡 채널 홈 URL에 명시된 ID\n");
      out.write("    });\n");
      out.write("  //]]>\n");
      out.write("</script>\n");
      out.write(" -->\n");
      out.write("\n");
      out.write("<!-- Start Footer -->\n");
      out.write("     <footer class=\"my-5 pt-5 text-muted text-center text-small album py-5 bg-light\">\n");
      out.write("    <p class=\"mb-1\">&copy; 2022–Team Bootcamp </p>\n");
      out.write("    <p>Hoping은 통신판매 중개자로서 통신판매의 당사자가 아니며 <br>\n");
      out.write("    고객지원을 제외한 상품의 예약, 이용 등과 관련한 의무와 책임 등 모든 거래에 대한 책임은 가맹점에게 있습니다.\n");
      out.write("    </p>\n");
      out.write("    <ul class=\"list-inline\">\n");
      out.write("      <li class=\"list-inline-item\"><a href=\"TermsHomepage.jsp\">이용약관</a></li>\n");
      out.write("      <li class=\"list-inline-item\"><a href=\"support.jsp\">Support</a></li>\n");
      out.write("      <li class=\"list-inline-item\"><a href=\"#\">Contact Us</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </footer>\n");
      out.write("    <!-- End Footer -->\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    </html>");
      out.write("\n");
      out.write("	<!-- Foot End -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
