/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-31 00:56:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CustomerOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.104.2\">\n");
      out.write("<title>ZOEN-주문결제창</title>\n");
      out.write("\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.kr/docs/5.2/examples/checkout/\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- Favicons -->\n");
      out.write("<link rel=\"apple-touch-icon\"\n");
      out.write("	href=\"/docs/5.2/assets/img/favicons/apple-touch-icon.png\"\n");
      out.write("	sizes=\"180x180\">\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.2/assets/img/favicons/favicon-32x32.png\"\n");
      out.write("	sizes=\"32x32\" type=\"image/png\">\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.2/assets/img/favicons/favicon-16x16.png\"\n");
      out.write("	sizes=\"16x16\" type=\"image/png\">\n");
      out.write("<link rel=\"manifest\" href=\"/docs/5.2/assets/img/favicons/manifest.json\">\n");
      out.write("<link rel=\"mask-icon\"\n");
      out.write("	href=\"/docs/5.2/assets/img/favicons/safari-pinned-tab.svg\"\n");
      out.write("	color=\"#712cf9\">\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.2/assets/img/favicons/favicon.ico\">\n");
      out.write("<meta name=\"theme-color\" content=\"#712cf9\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".bd-placeholder-img {\n");
      out.write("	font-size: 1.125rem;\n");
      out.write("	text-anchor: middle;\n");
      out.write("	-webkit-user-select: none;\n");
      out.write("	-moz-user-select: none;\n");
      out.write("	user-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( min-width : 768px) {\n");
      out.write("	.bd-placeholder-img-lg {\n");
      out.write("		font-size: 3.5rem;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-divider {\n");
      out.write("	height: 3rem;\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\n");
      out.write("	border-width: 1px 0;\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\n");
      out.write("		rgba(0, 0, 0, .15);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-vr {\n");
      out.write("	flex-shrink: 0;\n");
      out.write("	width: 1.5rem;\n");
      out.write("	height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bi {\n");
      out.write("	vertical-align: -.125em;\n");
      out.write("	fill: currentColor;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller {\n");
      out.write("	position: relative;\n");
      out.write("	z-index: 2;\n");
      out.write("	height: 2.75rem;\n");
      out.write("	overflow-y: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller .nav {\n");
      out.write("	display: flex;\n");
      out.write("	flex-wrap: nowrap;\n");
      out.write("	padding-bottom: 1rem;\n");
      out.write("	margin-top: -1px;\n");
      out.write("	overflow-x: auto;\n");
      out.write("	text-align: center;\n");
      out.write("	white-space: nowrap;\n");
      out.write("	-webkit-overflow-scrolling: touch;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 결제 진행 폼 -->\n");
      out.write("<link href=\"form-validation.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-light\">\n");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<main>\n");
      out.write("			<form action=\"order.do\" method=\"post\">\n");
      out.write("			<div class=\"py-5 text-center\">\n");
      out.write("				<h2>결제창</h2>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"row g-5\">\n");
      out.write("				<div class=\"col-md-5 col-lg-4 order-md-last\">\n");
      out.write("					<h4 class=\"d-flex justify-content-between align-items-center mb-3\">\n");
      out.write("						<span class=\"text-primary\">결제 상품 리스트</span> <span\n");
      out.write("							class=\"badge bg-primary rounded-pill\">1</span>\n");
      out.write("					</h4>\n");
      out.write("\n");
      out.write("\n");
      out.write("					\n");
      out.write("						<ul class=\"list-group mb-3\">\n");
      out.write("\n");
      out.write("							<li class=\"list-group-item d-flex justify-content-between lh-sm\">\n");
      out.write("								<div>\n");
      out.write("									<h6 class=\"my-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\n");
      out.write("									<small class=\"text-muted\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</small>\n");
      out.write("								</div> <span class=\"text-muted\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pSaleprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("							</li>\n");
      out.write("\n");
      out.write("							<li class=\"list-group-item d-flex justify-content-between\">\n");
      out.write("								<span>주문합계</span> <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pSaleprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<div class=\"col-md-7 col-lg-8\">\n");
      out.write("					<h4 class=\"mb-3\">주문자 정보</h4>\n");
      out.write("\n");
      out.write("					<div class=\"col-12\">\n");
      out.write("\n");
      out.write("\n");
      out.write("						<label for=\"firstName\" class=\"form-label\">이름</label> <input\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"firstName\"\n");
      out.write("							value=\"");
      out.print(session.getAttribute("CID") );
      out.write("\">\n");
      out.write("						<div class=\"invalid-feedback\"></div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"col-12\">\n");
      out.write("						<label for=\"phone\" class=\"form-label\">휴대폰번호</label>\n");
      out.write("						<div class=\"input-group has-validation\">\n");
      out.write("							<input type=\"text\" class=\"form-control\" id=\"phone\"\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.cPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("							<div class=\"invalid-feedback\"></div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"col-12\">\n");
      out.write("						<label for=\"address\" class=\"form-label\">주소</label> <input\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"address\"\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.cAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("						<div class=\"invalid-feedback\"></div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("					");
      out.write("\n");
      out.write("					<h4 class=\"mb-3\">결제방법</h4>\n");
      out.write("\n");
      out.write("					<div class=\"my-3\">\n");
      out.write("						<div class=\"form-check\">\n");
      out.write("							<input id=\"credit\" name=\"oPayment\" type=\"radio\"\n");
      out.write("								class=\"form-check-input\" checked=\"checked\" value=\"신용카드\">\n");
      out.write("							신용카드\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<div class=\"form-check\">\n");
      out.write("							<input id=\"debit\" name=\"oPayment\" type=\"radio\"\n");
      out.write("								class=\"form-check-input\" value=\"체크카드\">체크카드\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<div class=\"form-check\">\n");
      out.write("							<input id=\"deposit without a bankbook\" name=\"oPayment\"\n");
      out.write("								type=\"radio\" class=\"form-check-input\" value=\"무통장입금\">무통장입금\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("					<hr class=\"my-4\">\n");
      out.write("					<div class=\"form-check\">\n");
      out.write("						<input type=\"checkbox\" class=\"form-check-input\" id=\"agree\">\n");
      out.write("						<label class=\"agree\" for=\"agree\">회원 본인은 구매조건, 주문 내용 확인 및\n");
      out.write("							결제에 동의합니다.</label>\n");
      out.write("					</div>\n");
      out.write("					<br>\n");
      out.write("\n");
      out.write("					<button class=\"w-100 btn btn-primary btn-lg\" type=\"submit\">결제하기</button>\n");
      out.write("\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			</form>\n");
      out.write("		</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<script\n");
      out.write("			src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("			integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\"\n");
      out.write("			crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("		<script src=\"form-validation.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
