/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-30 16:17:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProductDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.104.2\">\n");
      out.write("<title>제품상세창</title>\n");
      out.write("\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.2/examples/starter-template/\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"../assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".bd-placeholder-img {\n");
      out.write("	font-size: 1.125rem;\n");
      out.write("	text-anchor: middle;\n");
      out.write("	-webkit-user-select: none;\n");
      out.write("	-moz-user-select: none;\n");
      out.write("	user-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( min-width : 768px) {\n");
      out.write("	.bd-placeholder-img-lg {\n");
      out.write("		font-size: 3.5rem;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-divider {\n");
      out.write("	height: 3rem;\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\n");
      out.write("	border-width: 1px 0;\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\n");
      out.write("		rgba(0, 0, 0, .15);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-vr {\n");
      out.write("	flex-shrink: 0;\n");
      out.write("	width: 1.5rem;\n");
      out.write("	height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bi {\n");
      out.write("	vertical-align: -.125em;\n");
      out.write("	fill: currentColor;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller {\n");
      out.write("	position: relative;\n");
      out.write("	z-index: 2;\n");
      out.write("	height: 2.75rem;\n");
      out.write("	overflow-y: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller .nav {\n");
      out.write("	display: flex;\n");
      out.write("	flex-wrap: nowrap;\n");
      out.write("	padding-bottom: 1rem;\n");
      out.write("	margin-top: -1px;\n");
      out.write("	overflow-x: auto;\n");
      out.write("	text-align: center;\n");
      out.write("	white-space: nowrap;\n");
      out.write("	-webkit-overflow-scrolling: touch;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("<link href=\"starter-template.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div class=\"col-lg-8 mx-auto p-4 py-md-5\">\n");
      out.write("		<header class=\"d-flex align-items-center pb-3 mb-5 border-bottom\">\n");
      out.write("			<a href=\"/\"\n");
      out.write("				class=\"d-flex align-items-center text-dark text-decoration-none\">\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"32\"\n");
      out.write("					class=\"me-2\" viewBox=\"0 0 118 94\" role=\"img\">\n");
      out.write("					<title>제품상세</title><path fill-rule=\"evenodd\"\n");
      out.write("						clip-rule=\"evenodd\"\n");
      out.write("						d=\"M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z\"\n");
      out.write("						fill=\"currentColor\"></path></svg> <span class=\"fs-4\">Zoen Shoes</span>\n");
      out.write("			</a>\n");
      out.write("		</header>\n");
      out.write("\n");
      out.write("		<main>\n");
      out.write("\n");
      out.write("			<div class=\"row g-5\">\n");
      out.write("\n");
      out.write("\n");
      out.write("				<div class=\"col-md-6\">\n");
      out.write("				\n");
      out.write("				\n");
      out.write("					<form action=\"detailOrder.do\" method=\"post\">\n");
      out.write("						<input type=\"hidden\" name=\"pId\" value=\"");
      out.print(session.getAttribute("PID") );
      out.write("\">\n");
      out.write("						<input type=\"hidden\" name=\"cId\" value=\"");
      out.print(session.getAttribute("CID") );
      out.write("\">\n");
      out.write("						\n");
      out.write("						<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pBrand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\n");
      out.write("						<p>상품번호 ");
      out.print(session.getAttribute("PID") );
      out.write("</p>\n");
      out.write("						<ul class=\"icon-list ps-0\">\n");
      out.write("							<br>\n");
      out.write("							<li class=\"d-flex align-items-start mb-1\">사이즈:\n");
      out.write("								");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("\n");
      out.write("\n");
      out.write("							<br>\n");
      out.write("							\n");
      out.write("							<li class=\"d-flex align-items-start mb-1\">색상:\n");
      out.write("								");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pColor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("							<br>\n");
      out.write("\n");
      out.write("							<li class=\"d-flex align-items-start mb-1\">가격: \n");
      out.write("							");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pSaleprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("							<br>\n");
      out.write("							\n");
      out.write("							<li class=\"d-flex align-items-start mb-1\">수량: \n");
      out.write("							<select name=\"quantity\" id=\"quantity\">\n");
      out.write("							  <option value=\"1\">1</option>\n");
      out.write("							  <option value=\"2\">2</option>\n");
      out.write("							  <option value=\"3\">3</option>\n");
      out.write("							  <option value=\"4\">4</option>\n");
      out.write("							  <option value=\"5\">5</option>\n");
      out.write("							  <option value=\"6\">6</option>\n");
      out.write("							  <option value=\"7\">7</option>\n");
      out.write("							  <option value=\"8\">8</option>\n");
      out.write("							</select>\n");
      out.write("							\n");
      out.write("							</li>\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							<br>\n");
      out.write("							<br>\n");
      out.write("							<ul>\n");
      out.write("								<button type=\"submit\" class=\"btn btn-success\" value=\"구매\">바로구매</button>\n");
      out.write("							</ul>\n");
      out.write("						</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			</form>\n");
      out.write("\n");
      out.write("		</main>\n");
      out.write("		<footer class=\"pt-5 my-5 text-muted border-top\"> Created by\n");
      out.write("			the Bootstrap team &middot; &copy; 2022 </footer>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"../assets/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
